#!/bin/bash
hummingmot_sync_upstream() {
	git remote add upstream git@github.com:hummingbot/hummingbot.git
	git fetch upstream master
	git stash --include-untracked
	# git stash -a save "message"
	git merge upstream/master user
	# git commit -am "after merge upstream/master with user"
	git remote set-head origin user
	git push
	git stash pop
	# git stash pop stash@"{0}"
}
hummingmot_sync_upstream

